[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['pip install -r backend/requirements-railway.txt']

[start]
cmd = 'cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT'
