[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install -r backend/requirements-railway.txt'
]

[start]
cmd = '/opt/venv/bin/uvicorn backend.main:app --host 0.0.0.0 --port $PORT'
